source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

use_frameworks!

pod 'FirebaseCore', :path => '../../../..'
pod 'FirebaseInstallations', :path => '../../../..'
pod 'FirebaseCoreDiagnostics', :path => '../../../..'
pod 'FirebaseABTesting', :path => '../../../..'

target 'InAppMessaging_Example_iOS' do
  platform :ios, '9.0'

  pod 'FirebaseInAppMessaging', :path => '../../../..'
  pod 'FirebaseDynamicLinks',  :path => '../../../..'

end
