source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

use_frameworks!

pod 'FirebaseCore', :path => '../../../..'
pod 'FirebaseInstallations', :path => '../../../..'
pod 'FirebaseCoreDiagnostics', :path => '../../../..'
pod 'GoogleDataTransport', :path => '../../../..'
pod 'GoogleUtilities', :path => '../../../..'
pod 'FirebaseABTesting', :path => '../../../..'
pod 'FirebaseInAppMessaging', :path => '../../../..'

target 'CustomSwiftUI' do
  platform :ios, '14.0'
  pod 'FirebaseInAppMessagingSwift', :path => '../../../..'
end
